CXXFLAGS=-g -std=c++11
CC=$(CXX)
INCS=$(shell ls *.h)

complex: complex.cpp 

complex_class: complex_class.cpp 

funcs: funcs.cpp 

hello: hello.cpp 

hello_nm: hello_nm.cpp 

mean: mean.cpp 

weather: weather.cpp

repo:
	-git commit -a 
	git push origin master

nocrud:
	rm *~
